# Basic Information 
title: Xiaoqian Shen
position: KAUST CS PhD
#affiliation: KAUST
email: xiaoqian.shen (at) kaust.edu.sa

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: minimal light
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light-theme.yliu.me/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?hl=en&user=uToGtIwAAAAJ
cv_link: assets/files/resume.pdf
github_link: https://github.com/xiaoqian-shen
linkedin: https://www.linkedin.com/in/xiaoqian-shen-759991264
twitter: https://twitter.com/xiaoqian_shen

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.jpg
#favicon: ./assets/img/favicon.png
#favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: false

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - minimal-light.gemspec
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - node_modules
